# service loadbalancer
apiVersion : v1
kind       : Service
metadata:
  name: autoscaler-service
  labels:
     owner: Alex
spec:
   selector:
      project: server_web
   ports:
     - name       : app-listener
       protocol   : TCP
       port       : 80 #for loadbalancer 
       targetPort : 80 # port on pod
   type: LoadBalancer
